<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Rule Analysis Memo</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Rule-Analysis-Memo_files/libs/clipboard/clipboard.min.js"></script>
<script src="Rule-Analysis-Memo_files/libs/quarto-html/quarto.js"></script>
<script src="Rule-Analysis-Memo_files/libs/quarto-html/popper.min.js"></script>
<script src="Rule-Analysis-Memo_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Rule-Analysis-Memo_files/libs/quarto-html/anchor.min.js"></script>
<link href="Rule-Analysis-Memo_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Rule-Analysis-Memo_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Rule-Analysis-Memo_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Rule-Analysis-Memo_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Rule-Analysis-Memo_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Rule Analysis Memo</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="intro" class="level2">
<h2 class="anchored" data-anchor-id="intro">Intro</h2>
<p>In the summer of 2024, the Supreme Court issued two landmark rulings – <em>Ohio v. EPA</em> on June 27, 2024, and <em>Loper Bright Enterprises v. Raimondo</em> on June 28, 2024 – that transformed the regulatory landscape for federal agencies. In <em>Ohio v. EPA</em>, the Court held that an agency’s failure to adequately respond to significant public comments during the notice-and-comment process renders its rules arbitrary and capricious. The following day, in <em>Loper Bright v. Raimondo</em>, the Court overruled Chevron deference, directing lower courts to interpret statutory ambiguities independently rather than deferring to agency interpretations. In doing so, the Court substantially reduced agency latitude in interpreting legislative “gray areas”.</p>
<p>We hypothesize that these decision created an environment where agencies are less likely to publish formal rules due to the increased logistical burden of addressing public comments post-<em>Ohio v. EPA</em> and the heightened risk of litigation over statutory interpretations post-<em>Loper Bright</em> likely discourage rulemaking. In addition, we propose a broader hypothesis: the overall proportion of formal rules has been decreasing since 2000. This decline is likely driven by a combination of factors. First, evolving expectations for transparency and adaptability have encouraged agencies to favor more flexible, informal governance mechanisms. Second, the cumulative impact of judicial constraints—exemplified by recent rulings—further disincentivizes the proliferation of formal rulemaking.</p>
<p>To investigate these hypotheses, we employ quantitative methods—specifically, regression-discontinuity and interrupted time series analyses—using the period following the release of Loper Bright Enterprises v. Raimondo (starting June 29, 2024) as a cutoff, complemented by a longitudinal analysis of rulemaking trends dating back to 2000. This study aims to empirically assess how these Supreme Court rulings, in tandem with broader administrative shifts, have impacted agency rulemaking behavior.</p>
</section>
<section id="running-code" class="level2">
<h2 class="anchored" data-anchor-id="running-code">Running Code</h2>
<p>Now, create plots from df data frame</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Rule-Analysis-Memo_files/figure-html/Total%20Rules%20Published%20Each%20Year%20(2000-2024)-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="Rule-Analysis-Memo_files/figure-html/Total%20Guidance%20Documents%20Published%20Each%20Year%20(2000-2024)-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="Rule-Analysis-Memo_files/figure-html/Total%20Documents%20Published%20Each%20Year%20(2000-2024)-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="Rule-Analysis-Memo_files/figure-html/Plot%204%20-%20Proportion%20of%20FDA%20Rules%20to%20Total%20Documents%20Each%20Year%20(2000-2024)-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="regression-discontinuity-analysis" class="level2">
<h2 class="anchored" data-anchor-id="regression-discontinuity-analysis">Regression Discontinuity Analysis</h2>
<p><span class="math display">\[
Y_i = \alpha + \tau D_i + \beta X_i + \gamma (D_i \times X_i) + \sum_{m=1}^{11} \delta_m M_{im} + \theta T_i + \epsilon_i
\]</span></p>
<p>Where:</p>
<ul>
<li><p>(<span class="math inline">\(Y_i\)</span>): Number of Rules Published in month (<span class="math inline">\(i\)</span>).</p></li>
<li><p>(<span class="math inline">\(\alpha\)</span>): Intercept term (baseline level of (<span class="math inline">\(Y\)</span>).</p></li>
<li><p>(<span class="math inline">\(D_i\)</span>): Treatment Indicator for month (<span class="math inline">\(i\)</span>). <span class="math inline">\(D_i\)</span> = 1 if month <span class="math inline">\(i\)</span> is after June 2024 and 0 otherwise.</p></li>
<li><p>(<span class="math inline">\(X_i\)</span>): Running Variable representing the distance from the cutoff (June 2024) for month <span class="math inline">\(i\)</span>). Measured in months: <span class="math inline">\(X_i\)</span> = Number of months since June 2024</p>
<ul>
<li><p>(<span class="math inline">\(X_i &gt; 0\)</span>): Post-June 2024 (treatment group)</p></li>
<li><p>(<span class="math inline">\(X_i &lt; 0\)</span>): Pre-June 2024 (control group)</p></li>
</ul></li>
<li><p>(<span class="math inline">\(\beta\)</span>): The Treatment Effect</p></li>
<li><p>(<span class="math inline">\(\gamma\)</span>): Coefficient for the interaction between treatment and distance, capturing the change in slope after the cutoff.</p></li>
<li><p>(<span class="math inline">\(M_{im}\)</span>): Monthly Dummy Variables for each month ( <span class="math inline">\(m\)</span>, January to December), excluding one month to avoid multicollinearity (January is the reference category).</p></li>
<li><p>(<span class="math inline">\(\delta_m\)</span>): Coefficients for each monthly dummy variable, capturing the effect of being in month (<span class="math inline">\(m\)</span>) relative to the reference month.</p></li>
<li><p>(<span class="math inline">\(T_i\)</span>): Presidential Transition Indicator for month (<span class="math inline">\(i\)</span>). <span class="math inline">\(T_i = 1\)</span> if the month is either September–December of an election year or January of the year following an election year, and 0 otherwise.</p></li>
<li><p>(<span class="math inline">\(\theta\)</span>): Coefficient capturing the effect associated with presidential transition years.</p></li>
<li><p>(<span class="math inline">\(\epsilon_i\)</span>): Error Term capturing unobserved factors affecting (<span class="math inline">\(Y_i\)</span>).</p></li>
</ul>
</section>
<section id="analysis-for-fda-rules" class="level2">
<h2 class="anchored" data-anchor-id="analysis-for-fda-rules">Analysis for FDA Rules</h2>
<p>The model for FDA Rules shows a strongly significant negative relationship with the running variable (distance, p &lt; 2e-16), suggesting that number of monthly FDA rules published decreases as time progresses. The treatment effect is positive but not statistically significant (p = 0.1068), and the interaction between treatment and distance is not significant either. Several seasonal components (e.g., month^C, month^5, month^7, and month^8) are significant, while the presidential transition indicator does not have a significant effect.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = rules ~ treatment * distance + month + transition, 
    data = rd_data_all)

Residuals:
    Min      1Q  Median      3Q     Max 
-9.6913 -3.0201 -0.6288  2.6139 17.4341 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         3.755796   0.536401   7.002 1.83e-11 ***
treatment           7.070208   4.370240   1.618 0.106814    
distance           -0.032425   0.003142 -10.319  &lt; 2e-16 ***
month.L             0.489466   0.938527   0.522 0.602407    
month.Q             0.569979   0.943413   0.604 0.546215    
month.C             3.130836   0.928067   3.374 0.000845 ***
month^4            -0.046948   0.915088  -0.051 0.959119    
month^5             1.828582   0.919144   1.989 0.047612 *  
month^6             1.048743   0.917782   1.143 0.254128    
month^7            -2.254139   0.916416  -2.460 0.014500 *  
month^8             2.040164   0.914325   2.231 0.026439 *  
month^9            -1.555138   0.916660  -1.697 0.090882 .  
month^10            0.584463   0.916052   0.638 0.523972    
month^11           -0.304525   0.915965  -0.332 0.739785    
transition          0.957589   1.109688   0.863 0.388901    
treatment:distance -1.288350   1.135088  -1.135 0.257323    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.571 on 284 degrees of freedom
Multiple R-squared:  0.3304,    Adjusted R-squared:  0.2951 
F-statistic: 9.343 on 15 and 284 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The FDA Rules model (6‑month window) yields an insignificant treatment effect of 7.00 (p = 0.2491). The distance coefficient (0.3143, p = 0.7857) is not significant and the interaction between treatment and distance is borderline (–4.95, p = 0.0660). Overall, the model has an R-squared of 0.50 (adjusted R-squared = 0.21) with a residual standard error of 4.65.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = rules ~ treatment * distance, data = rd_data_band)

Residuals:
   Min     1Q Median     3Q    Max 
-5.905 -1.645 -1.014  0.569 13.752 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)          4.9524     4.1884   1.182    0.271
treatment            4.7810     6.8241   0.701    0.503
distance             0.3143     1.3834   0.227    0.826
treatment:distance  -1.1429     1.9564  -0.584    0.575

Residual standard error: 5.787 on 8 degrees of freedom
Multiple R-squared:  0.1158,    Adjusted R-squared:  -0.2158 
F-statistic: 0.3491 on 3 and 8 DF,  p-value: 0.7911</code></pre>
</div>
</div>
</section>
<section id="analysis-for-fda-guidance-documents" class="level2">
<h2 class="anchored" data-anchor-id="analysis-for-fda-guidance-documents">Analysis for FDA Guidance Documents</h2>
<p>The analysis for Guidance Documents indicates that distance has a significant positive effect (p = 0.000426), implying an increase in guidance documents as time increases. However, both the treatment effect and its interaction with distance are not statistically significant. Only one seasonal component (month.L) reaches significance, and the overall explanatory power of the model is low (Adjusted R-squared = 0.04379).</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = guidance ~ treatment * distance + month + transition, 
    data = rd_data_all)

Residuals:
    Min      1Q  Median      3Q     Max 
 -9.589  -2.626  -0.648   1.768 101.740 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         8.229625   0.830036   9.915  &lt; 2e-16 ***
treatment           6.705764   6.762581   0.992 0.322238    
distance            0.017337   0.004862   3.566 0.000426 ***
month.L             3.201098   1.452292   2.204 0.028314 *  
month.Q             0.101349   1.459852   0.069 0.944701    
month.C             0.094146   1.436106   0.066 0.947777    
month^4            -1.880147   1.416022  -1.328 0.185321    
month^5            -1.783766   1.422298  -1.254 0.210821    
month^6            -0.983266   1.420191  -0.692 0.489285    
month^7            -1.882487   1.418077  -1.327 0.185412    
month^8             0.213132   1.414841   0.151 0.880366    
month^9            -1.377575   1.418455  -0.971 0.332285    
month^10           -0.444590   1.417513  -0.314 0.754024    
month^11           -0.479155   1.417379  -0.338 0.735570    
transition          0.531885   1.717150   0.310 0.756979    
treatment:distance -1.453692   1.756453  -0.828 0.408575    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.073 on 284 degrees of freedom
Multiple R-squared:  0.09176,   Adjusted R-squared:  0.04379 
F-statistic: 1.913 on 15 and 284 DF,  p-value: 0.02188</code></pre>
</div>
</div>
<p>The Guidance Documents model (6‑month window) shows a significant intercept (5.48, p = 0.0433) and a significant treatment effect (10.21, p = 0.0275). The distance effect is not significant (–0.1429, p = 0.8513), while the transition indicator is nearly significant (11.11, p = 0.0517) and the treatment:distance interaction is borderline (–3.31, p = 0.0633). This model explains a fair amount of variation (R-squared = 0.69, adjusted R-squared = 0.51).</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = guidance ~ treatment * distance, data = rd_data_band)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.2857 -1.9429 -0.5667  1.5452  7.5429 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)          5.4762     2.7778   1.971   0.0842 .
treatment            8.7238     4.5258   1.928   0.0901 .
distance            -0.1429     0.9175  -0.156   0.8801  
treatment:distance  -0.7714     1.2975  -0.595   0.5686  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.838 on 8 degrees of freedom
Multiple R-squared:  0.4465,    Adjusted R-squared:  0.2389 
F-statistic: 2.151 on 3 and 8 DF,  p-value: 0.1719</code></pre>
</div>
</div>
</section>
<section id="analysis-for-total-fda-documents-rules-guidance" class="level2">
<h2 class="anchored" data-anchor-id="analysis-for-total-fda-documents-rules-guidance">Analysis for Total FDA Documents (Rules + Guidance)</h2>
<p>In the Total Documents model, the distance variable is significantly negatively related to the total count (p = 0.0138), suggesting a decline in total documents with increasing distance from the cutoff. The treatment effect and its interaction with distance are not significant, although some seasonal factors (notably month.L and month^7) are. The model fit is modest, with an Adjusted R-squared of 0.03962.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = total_documents ~ treatment * distance + month + 
    transition, data = rd_data_all)

Residuals:
    Min      1Q  Median      3Q     Max 
-14.131  -4.319  -1.042   3.125 106.353 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        11.985421   1.039788  11.527   &lt;2e-16 ***
treatment          13.775971   8.471502   1.626   0.1050    
distance           -0.015088   0.006091  -2.477   0.0138 *  
month.L             3.690564   1.819290   2.029   0.0434 *  
month.Q             0.671328   1.828761   0.367   0.7138    
month.C             3.224982   1.799014   1.793   0.0741 .  
month^4            -1.927095   1.773855  -1.086   0.2782    
month^5             0.044816   1.781717   0.025   0.9800    
month^6             0.065477   1.779077   0.037   0.9707    
month^7            -4.136626   1.776428  -2.329   0.0206 *  
month^8             2.253296   1.772375   1.271   0.2046    
month^9            -2.932712   1.776903  -1.650   0.1000 .  
month^10            0.139874   1.775723   0.079   0.9373    
month^11           -0.783679   1.775554  -0.441   0.6593    
transition          1.489475   2.151078   0.692   0.4892    
treatment:distance -2.742043   2.200314  -1.246   0.2137    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.861 on 284 degrees of freedom
Multiple R-squared:  0.0878,    Adjusted R-squared:  0.03962 
F-statistic: 1.822 on 15 and 284 DF,  p-value: 0.03137</code></pre>
</div>
</div>
<p>In the Total Documents model, the distance variable is significantly negatively related to the total count (p = 0.0138), suggesting a decline in total documents with increasing distance from the beginning of the dataset. The treatment effect and its interaction with distance are not significant, although some seasonal factors (notably month.L and month^7) are. The model fit is modest, with an Adjusted R-squared of 0.03962.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = total_documents ~ treatment * distance, data = rd_data_band)

Residuals:
     Min       1Q   Median       3Q      Max 
-10.1905  -2.6286  -0.6095   0.6357  21.2952 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)         10.4286     6.4590   1.615    0.145
treatment           13.5048    10.5235   1.283    0.235
distance             0.1714     2.1333   0.080    0.938
treatment:distance  -1.9143     3.0170  -0.634    0.543

Residual standard error: 8.924 on 8 degrees of freedom
Multiple R-squared:  0.2717,    Adjusted R-squared:  -0.00135 
F-statistic: 0.9951 on 3 and 8 DF,  p-value: 0.443</code></pre>
</div>
</div>
</section>
<section id="analysis-for-proportion-of-fda-rules-to-total-documents" class="level2">
<h2 class="anchored" data-anchor-id="analysis-for-proportion-of-fda-rules-to-total-documents">Analysis for Proportion of FDA Rules to Total Documents</h2>
<p>The proportion model shows a highly significant negative effect of distance (p &lt; 2e-16), indicating that the proportion of rules declines as one progresses through the time period. The treatment effect and its interaction are not significant, but some seasonal effects (month.L and month.C) are statistically significant. This model has a comparatively higher explanatory power (Adjusted R-squared = 0.367).</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = proportion_rules ~ treatment * distance + month + 
    transition, data = rd_data_all)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.54491 -0.12520  0.01316  0.12175  0.56615 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         0.3490678  0.0232422  15.019   &lt;2e-16 ***
treatment           0.0607106  0.1893618   0.321   0.7487    
distance           -0.0017270  0.0001362 -12.684   &lt;2e-16 ***
month.L            -0.0822513  0.0406662  -2.023   0.0441 *  
month.Q             0.0480820  0.0408779   1.176   0.2405    
month.C             0.0913557  0.0402130   2.272   0.0238 *  
month^4             0.0050466  0.0396506   0.127   0.8988    
month^5             0.0617028  0.0398264   1.549   0.1224    
month^6             0.0327470  0.0397674   0.823   0.4109    
month^7             0.0132121  0.0397082   0.333   0.7396    
month^8            -0.0123213  0.0396175  -0.311   0.7560    
month^9            -0.0167641  0.0397188  -0.422   0.6733    
month^10            0.0250676  0.0396924   0.632   0.5282    
month^11           -0.0144518  0.0396886  -0.364   0.7160    
transition         -0.0199279  0.0480826  -0.414   0.6789    
treatment:distance -0.0123204  0.0491832  -0.251   0.8024    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1981 on 284 degrees of freedom
Multiple R-squared:  0.3988,    Adjusted R-squared:  0.367 
F-statistic: 12.56 on 15 and 284 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The Proportion model (6‑month window) displays a significant intercept (0.4995, p = 0.0108); however, the treatment (–0.1174, p = 0.6399), distance (0.0320, p = 0.5255), transition (0.1636, p = 0.6139), and their interaction (–0.08065, p = 0.4379) are not statistically significant. With an adjusted R-squared of –0.2938, this model has poor explanatory power for the proportion of FDA rules.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = proportion_rules ~ treatment * distance, data = rd_data_band)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.19183 -0.14195 -0.01236  0.09652  0.31029 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)         0.49952    0.13848   3.607  0.00691 **
treatment          -0.13920    0.22562  -0.617  0.55442   
distance            0.03203    0.04574   0.700  0.50357   
treatment:distance -0.04326    0.06468  -0.669  0.52246   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1913 on 8 degrees of freedom
Multiple R-squared:  0.1439,    Adjusted R-squared:  -0.1772 
F-statistic: 0.4481 on 3 and 8 DF,  p-value: 0.7255</code></pre>
</div>
</div>
<p>Now, let’s visualize the RD regression, displaying the number of rules published in the 7 months before and after the cutoff date</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>